services:
  extract:
    build: .
    env_file:
      - .env
    volumes:
      - ./files:/app/files
  test:
    build:
      dockerfile: test.Dockerfile
    volumes:
      - ./tests:/app/tests
      - ./files:/app/files/
