services:
  extract:
    build: .
    command:
      - "report"
      - ""
      - ""
      - "--timeout=60"
      - "--concurrency=1"
    volumes:
      - ./files:/app/files
  test:
    build:
      dockerfile: test.Dockerfile
    volumes:
      - ./tests:/app/tests
      - ./files:/app/files/
